// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAXCZtpXjVl-2tcszYA6smR7PIholA9Fc',
    appId: '1:427109559549:web:dca991a473b4d5822ca294',
    messagingSenderId: '427109559549',
    projectId: 'sokodirect-54ac8',
    authDomain: 'sokodirect-54ac8.firebaseapp.com',
    storageBucket: 'sokodirect-54ac8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcr6cjc2gYeCEf9BFQ_LquvDwn6nQpsBU',
    appId: '1:427109559549:android:94a3437de671cc092ca294',
    messagingSenderId: '427109559549',
    projectId: 'sokodirect-54ac8',
    storageBucket: 'sokodirect-54ac8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQmYSLpERTgKmOdvGNxvJuYq_gxxoAm4s',
    appId: '1:427109559549:ios:a8001c61f244ddbb2ca294',
    messagingSenderId: '427109559549',
    projectId: 'sokodirect-54ac8',
    storageBucket: 'sokodirect-54ac8.firebasestorage.app',
    iosClientId:
        '427109559549-mdqae2tn699iplp06t9vtnptvou3s4pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokoDirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQmYSLpERTgKmOdvGNxvJuYq_gxxoAm4s',
    appId: '1:427109559549:ios:a8001c61f244ddbb2ca294',
    messagingSenderId: '427109559549',
    projectId: 'sokodirect-54ac8',
    storageBucket: 'sokodirect-54ac8.firebasestorage.app',
    iosClientId:
        '427109559549-mdqae2tn699iplp06t9vtnptvou3s4pa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sokoDirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAXCZtpXjVl-2tcszYA6smR7PIholA9Fc',
    appId: '1:427109559549:web:2cf77a7dc301dcf02ca294',
    messagingSenderId: '427109559549',
    projectId: 'sokodirect-54ac8',
    authDomain: 'sokodirect-54ac8.firebaseapp.com',
    storageBucket: 'sokodirect-54ac8.firebasestorage.app',
  );
}
