import 'package:cloud_firestore/cloud_firestore.dart';
import '../../offers/domain/offer.dart';
import '../domain/transaction_model.dart';
import '../domain/transaction_repository.dart';

/// Real Firestore implementation.
/// Collection: "transactions"
/// Document ID: auto-generated by Firestore.
///
/// Note: Firestore stores dates as its own Timestamp type, not plain
/// strings — so this repository converts to/from Timestamp itself,
/// instead of using TransactionModel.toMap()/fromMap() directly (those
/// stay string-based, useful for tests or other non-Firestore contexts).
class TransactionFirestoreRepository implements TransactionRepository {
  final _transactionsRef = FirebaseFirestore.instance.collection('transactions');

  @override
  Future<TransactionModel> createFromOffer(Offer offer) async {
    final amount = offer.pricePerKg * offer.quantityKg;
    final now = DateTime.now();

    final docRef = await _transactionsRef.add({
      'offerId': offer.id,
      'buyerId': offer.buyerId,
      'farmerId': offer.farmerId,
      'amount': amount,
      'escrowStatus': 'held',
      'deliveryConfirmed': false,
      'createdAt': Timestamp.fromDate(now),
    });

    return TransactionModel(
      id: docRef.id,
      offerId: offer.id,
      buyerId: offer.buyerId,
      farmerId: offer.farmerId,
      amount: amount,
      escrowStatus: 'held',
      deliveryConfirmed: false,
      createdAt: now,
    );
  }

  @override
  Future<void> confirmDelivery(String transactionId) async {
    await _transactionsRef.doc(transactionId).update({
      'escrowStatus': 'released',
      'deliveryConfirmed': true,
    });
  }

  @override
  Future<TransactionModel> getTransaction(String transactionId) async {
    final doc = await _transactionsRef.doc(transactionId).get();
    if (!doc.exists) {
      throw Exception('Transaction not found: $transactionId');
    }
    final data = doc.data()!;
    return TransactionModel(
      id: doc.id,
      offerId: data['offerId'] as String,
      buyerId: data['buyerId'] as String,
      farmerId: data['farmerId'] as String,
      amount: (data['amount'] as num).toDouble(),
      escrowStatus: data['escrowStatus'] as String,
      deliveryConfirmed: data['deliveryConfirmed'] as bool,
      createdAt: (data['createdAt'] as Timestamp).toDate(),
    );
  }
}
